// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdb0zPae1FIoLNyWF7Z5uscOw6FfcMiw',
    appId: '1:265057195582:web:07d90baa07a21fac75636f',
    messagingSenderId: '265057195582',
    projectId: 'nudgeappbyb',
    authDomain: 'nudgeappbyb.firebaseapp.com',
    storageBucket: 'nudgeappbyb.firebasestorage.app',
    measurementId: 'G-RBCL7KV68K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-5V_Kff8yc18GNt-oCZbWRHECnW9VvOw',
    appId: '1:265057195582:android:266187c45291995c75636f',
    messagingSenderId: '265057195582',
    projectId: 'nudgeappbyb',
    storageBucket: 'nudgeappbyb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDptTZPxpJm74wsDV5YMJMEKh3GdKKtloA',
    appId: '1:265057195582:ios:ede5d5809598631a75636f',
    messagingSenderId: '265057195582',
    projectId: 'nudgeappbyb',
    storageBucket: 'nudgeappbyb.firebasestorage.app',
    iosBundleId: 'com.example.ktbNudges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDptTZPxpJm74wsDV5YMJMEKh3GdKKtloA',
    appId: '1:265057195582:ios:ede5d5809598631a75636f',
    messagingSenderId: '265057195582',
    projectId: 'nudgeappbyb',
    storageBucket: 'nudgeappbyb.firebasestorage.app',
    iosBundleId: 'com.example.ktbNudges',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhdb0zPae1FIoLNyWF7Z5uscOw6FfcMiw',
    appId: '1:265057195582:web:16c8c89dcd1da1bd75636f',
    messagingSenderId: '265057195582',
    projectId: 'nudgeappbyb',
    authDomain: 'nudgeappbyb.firebaseapp.com',
    storageBucket: 'nudgeappbyb.firebasestorage.app',
    measurementId: 'G-NYVH2S1RZY',
  );

}